# Generated by Django 3.2.19 on 2023-06-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_subscriber',
            new_name='is_subscribed',
        ),
    ]
